### ISSUE TITLE
One step sigup/login and join.

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#113]
Can we create a special URL for Organizations that are a step, sign in/signup and join?
Maybe a QR code also.

The link takes a user to a page.
The page has:
- option to sign in
- Fields for the new user (these are hidden if the user signs in)
- Custom Org membership fields
- Org payment form

**Comment by pprolancer** [comment]
New user, signup, only show these fields

name :required
phone: required
email: required
DOB
The other field the user can add/edit in user profile.

**Comment by pprolancer** [comment]
Change the scenario of signup to create Member object before activation email.

**Comment by pprolancer** [comment]
- [ ] Need to be clear email will be user name

- [ ] Need to let user know they will need to activate from the email link before they login.

- [ ] Form should ask for email twice.

- [ ] Admin can fix email and have a option in Admin to resend. Don't need on the public UI for now.
