### ISSUE TITLE
Signup page caption/text

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#118]
Need text (caption) for the create account page.

<img width="481" alt="Screenshot 2022-12-13 at 8 16 13 AM" src="https://user-images.githubusercontent.com/232564/207374349-36bae2f9-aad9-4bc5-ad16-128c2d8b19c9.png">

**Comment by aishkrish95** [comment]
Sign up on We Race Here
Sign up to begin finding bike racing events and to view your race results.
Clubs and organizations, sign up to list and manage your events and results.

*Aishwarya Krishnamoorthy*
Director of Marketing and Communications, Bicycle Colorado & the Denver
Streets Partnership
Pronouns: she/her/hers
1525 Market Street, Suite 100
Denver, CO 80202
Phone: (720) 504-8515‬
bicyclecolorado.org
<https://www.bicyclecolorado.org/join-us/become-a-member/>
