### ISSUE TITLE
Global setting to edit event tags

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#135]
For the list of event tags, add a global preference in the /admin to define that list.
Add all current tags to this list.

![Image](https://user-images.githubusercontent.com/232564/211170250-a4d82258-9912-4d2d-aefc-fcaf049cece0.png)

**Comment by vincentdavis** [comment]
Hard coded tags are defined here:
[TAGS](https://github.com/we-race-here/wrh-organization/blob/1ca404b12876bfdb57b7bb094839caf3be16c150/wrh_organization/FRONTEND/wrh_organization_ui/src/Constants.js#L129)

Add Global preference like here
[Preferance](https://github.com/we-race-here/wrh-organization/blob/1ca404b12876bfdb57b7bb094839caf3be16c150/wrh_organization/apps/cycling_org/dynamic_preferences_registry.py)

**Comment by karthicksakkaravarti** [comment]
https://github.com/we-race-here/wrh-organization/pull/148
