### ISSUE TITLE
Add google maps to Event. Event location

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#141]
An example of what BC currently has is:
https://www.bicyclecolorado.org/event/2023-table-mountain-mid-week-race-12/

![Image](https://user-images.githubusercontent.com/232564/211686260-8b905ea5-3525-43c6-b1a7-903672ea1516.png)

The Admin UI for adding events looks like:

![Image](https://user-images.githubusercontent.com/232564/211686298-bb3f6422-c760-4972-8586-31eba78d63fa.png)

I like this UI because I can search for an address or drop a pin.

@karthicksakkaravarti Please propose how do this first. I mean which API, or just embed?
Maybe this [vue-google-maps](https://www.digitalocean.com/community/tutorials/vuejs-vue-google-maps)

What API keys do you need?

**Comment by karthicksakkaravarti** [comment]
https://github.com/we-race-here/wrh-organization/pull/151
