### ISSUE TITLE
Adding user to Org if user email is not lowercase.

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#164]
Deker created a new account, I was not able to add him to rmccc org. I was not able to find his email. Maybe this was because his email/username had a capital "R" Rmccc.president@....
I tried changing this to lowercase and it still did not work. Maybe it is a different problem

![Image](https://user-images.githubusercontent.com/232564/215350192-f3faba4f-484f-4229-b5ab-a345c727cee9.png)

![Image](https://user-images.githubusercontent.com/232564/215350206-143fa3e5-0d05-44f8-b6cf-b56abfb3e6b7.png)

**Comment by vincentdavis** [comment]
@pprolancer Need to make usernames lower case also.

**Comment by vincentdavis** [comment]
@pprolancer Not sure if this is done.

**Comment by pprolancer** [comment]
@vincentdavis 
Yes this is done
