### ISSUE TITLE
Change wording on Org membership for for BC donation.

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#169]
If you look here:

https://weracehere.org/static/vue/index.html#/signup-and-join-org/4

It should say:
`Please donate to support this We Race Here project and Bicycle Colorado`

![Image](https://user-images.githubusercontent.com/232564/215852324-5a0e83aa-d28f-4ce2-9f64-7661468a68cf.png)

**Comment by aishkrish95** [comment]
Hi Vincent! Just checking - was this actually being assigned to me to do or
is it just to track this ask? I apologize, but I am scrambling to prepare
for our conference on Monday and don't have the time to learn how to do
this and make this change. Thank you and I am sorry if this adds more to
your plate!

*Aishwarya Krishnamoorthy*
Director of Marketing and Communications, Bicycle Colorado & the Denver
Streets Partnership
Pronouns: she/her/hers
1525 Market Street, Suite 100
Denver, CO 80202
Phone: (720) 504-8515‬
bicyclecolorado.org
<https://www.bicyclecolorado.org/join-us/become-a-member/>

**Comment by vincentdavis** [comment]
@aishkrish95 This is just so you can track the issue.
