### ISSUE TITLE
Add ical link to subscribe to public calendar.

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#172]
The goal of this issue.
1. Allow people to subscribe to the public calendar feed with there, outlook, Apple calendar, and google calendar.

The focus of this issue is to provide the backend needed to generate and provide calendar feeds.

Look at this, Not sure it is the right solution but seems ok, 

https://django-ical.readthedocs.io/en/latest/usage.html#example

https://lauren-c-stephen.medium.com/subscribe-to-an-icalendar-feed-in-google-calendar-and-solve-update-issues-79b4e84b3c64

**Comment by karthicksakkaravarti** [comment]
2.On the event page, link to "add to calendar," Which adds that event to a user calendar.

**Comment by karthicksakkaravarti** [comment]
https://dev2.weracehere.org/feed/calendar/ics
