### ISSUE TITLE
Submit event link on event list view

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#292]
Add a link to the submit event form on the event list view

[list view](https://events.bicyclecolorado.org/events/)

Link to https://www.bicyclecolorado.org/events-2/submit-an-event/

Mockup
<img width="1135" alt="Screenshot 2023-03-29 at 11 42 38 AM" src="https://user-images.githubusercontent.com/232564/228623913-ad7b04bb-fc7f-4942-ab57-c36ca38a1e9e.png">

**Comment by vincentdavis** [comment]
@karthicksakkaravarti 
This is not displaying right.
- Its creating a second row.
- Submit link color is wrong, text too large, and needs to be on the left.

<img width="1383" alt="Screenshot 2023-04-03 at 5 38 19 AM" src="https://user-images.githubusercontent.com/232564/229498645-bce58da4-3946-4d54-80a7-fb1a534d40c6.png">

**Comment by karthicksakkaravarti** [comment]
Fixed
