### ISSUE TITLE
Add insert event video and event maps option.

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#294]
Add to event form fields to add videos (example: youtube) and maps (example: ridewithgps.com) iframes.
https://ridewithgps.com/help/tour-embed

These would be displaced between the about text and detail test on the event detail view like [`https://events.bicyclecolorado.org/event/8/`](https://events.bicyclecolorado.org/event/8/)

**Comment by karthicksakkaravarti** [comment]
is it ok? any thing else have to add ?
