### ISSUE TITLE
Replace current map with field to paste iframe link from google maps

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#295]
Remove the google maps from the event form (leave the backend code for now but add a TODO to remove later.
Add a new field for "Event Location Map" with helper text. "Paste google maps embed link"
This new field can be stored in the more_data json as {'event_location': iframe url}

**Comment by vincentdavis** [comment]
@karthicksakkaravarti 
Updated plan,
Add drop pin UI to current map admin UI

**Comment by karthicksakkaravarti** [comment]
Done
