### ISSUE TITLE
Show usac and BC featured icons below Event Detail text

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#297]
If featured or USAC permitted
![Screenshot 2023-03-29 at 12 41 55 PM](https://user-images.githubusercontent.com/232564/228637113-951a98c5-431e-4428-8149-73dca8f1efb1.png)
.

**Comment by vincentdavis** [comment]
@karthicksakkaravarti 
The space here is too big.
<img width="264" alt="Screenshot 2023-04-03 at 5 35 29 AM" src="https://user-images.githubusercontent.com/232564/229498187-0c4c7f10-c2ee-4d15-b280-daeca1b610a8.png">

**Comment by karthicksakkaravarti** [comment]
Done
