### ISSUE TITLE
Calculate points from race series results

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#52]
We have:
- race series
- race series results (from a download upload to assign category/place) (we have a view for results (without points)
- Points UI. Assign points for example 1st = 20points ...
- Race series points standing, calculated from results and points Need ui to view and filter by race and or category

**Comment by pprolancer** [comment]
@vincentdavis 
This should be fixed. please review that

**Comment by vincentdavis** [comment]
basic features complete
