### ISSUE TITLE
Default race result sort on home page.

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#54]
https://dev.weracehere.org/static/vue/index.html#/race-results
Currently, the 99999 which means DNF (Did not Finish) or DNS (Did not start) are listed first. 
- The default sort should be Newest first, then the lowest finish place (1st place first)
- Filter our DNS/DNS (99999) by default with an optional Show "DNF/DNS" results

**Comment by pprolancer** [comment]
@vincentdavis 
This is done!
