### ISSUE TITLE
Home page, user not logged in.

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#64]
https://dev.weracehere.org/static/vue/index.html#/home

For users not logged in, the main/home page should have the following content.

- no side menu
- Something at the top/center encourages user to log in or create an account.
- List of upcoming events. Link to the event page, calendar search page
- List of recent results (event name only, click to get details), Links to results page
- List of orgs "Teams" Links to Team search page
- List or orgs "Regional" Links to the Regional org search page.

**Comment by pprolancer** [comment]
Hi @vincentdavis 
This is done!
